Vive-20 Верстка авторизации и регистрации
frontend-park-mail-ru/2023_2_VIVE pull request #2
Opened 2023-09-28 21:30 UTC by Butters7

2023-09-28 21:47 UTC, DPeshkoff requested changes
в остальных файлах такие же замечания

2023-09-28 21:47 UTC, DPeshkoff commented on static/img/favicon.png
https://favicon.io/

2023-09-28 21:47 UTC, DPeshkoff commented on static/css/body.css
> +    background-color: #F7F7F7;
у нас есть такая переменная)

2023-09-28 21:47 UTC, DPeshkoff commented on static/css/body.css
> +    height: 23px;
предпочтительны значения, которые кратны [4 или 8](https://habr.com/ru/companies/productivity_inside/articles/319700/)

2023-09-28 21:47 UTC, DPeshkoff commented on static/css/body.css
> +    border: 0px;
можно без px

2023-09-28 21:47 UTC, DPeshkoff commented on static/css/body.css
> +    font-family: 'Acumin', sans-serif;
я бы добавил больше фоллбек-шрифтов

2023-09-28 21:47 UTC, DPeshkoff commented on static/css/body.css
> +footer {
вообще обычно не стоит навешивать на сами элементы, но на футер норм, думаю)

2023-09-28 21:47 UTC, DPeshkoff commented on static/fonts/Roboto.ttf
TTF - немного устаревший формат из 80-х. В современных браузерах (а мы делаем проект для последних версий) предпочтительнее использовать [WOFF2 ](https://web.dev/font-best-practices/#use-woff2), который позволяет снизить размер хоть на 30% от оригинального, а это поможет сделать перформанс лучше)

2023-09-28 21:47 UTC, DPeshkoff commented on templates/applicant_reg.html
> +<html lang="en">
Nepravda, eto ne angliyskiy

2023-09-28 21:47 UTC, DPeshkoff commented on templates/applicant_reg.html
> +    <title>Hunt&Hire</title>
Еще можно накинуть мета-тег для описания страницы и еще [кучу всего интересного](https://habr.com/ru/companies/htmlacademy/articles/563894/)

2023-09-28 21:47 UTC, DPeshkoff commented on templates/applicant_reg.html
> +            <div style="display: flex;">
Инлайн-стили - не очень, их лучше избегать

2023-09-28 21:47 UTC, DPeshkoff commented on templates/applicant_reg.html
> +            <span class="default-text" style="font-size: x-large;">Регистрация</span>
И тут!

2023-09-28 21:47 UTC, DPeshkoff commented on templates/applicant_reg.html
> +            <div class="input"><input type="text" class="input-in" placeholder="Имя"></div>
Кажется, инпутам нужны еще и уникальные id)

2023-09-28 21:47 UTC, DPeshkoff commented on templates/applicant_reg.html
> +                    <p class="footer-text" style="font-size: x-large;">Своей Мечты Здесь</p>
А почему каждое слово с заглавной буквы?

2023-09-30 15:38 UTC, Butters7 commented on templates/applicant_reg.html
> +                    <p class="footer-text" style="font-size: x-large;">Своей Мечты Здесь</p>
исправил

2023-09-30 15:39 UTC, Butters7 commented on templates/applicant_reg.html
> +            <div class="input"><input type="text" class="input-in" placeholder="Имя"></div>
исправил

2023-09-30 15:39 UTC, Butters7 commented on templates/applicant_reg.html
> +            <span class="default-text" style="font-size: x-large;">Регистрация</span>
исправил

2023-09-30 15:39 UTC, Butters7 commented on templates/applicant_reg.html
> +            <div style="display: flex;">
исправил

2023-09-30 15:39 UTC, Butters7 commented on static/css/body.css
> +    border: 0px;
исправил

2023-09-30 15:42 UTC, Butters7 commented on static/css/body.css
> +    height: 23px;
исправил

2023-09-30 15:42 UTC, Butters7 commented on static/img/favicon.png
поменял

2023-09-30 15:53 UTC, Butters7 commented on static/css/body.css
> +    background-color: #F7F7F7;
Вынес переменные в root)

2023-10-02 09:29 UTC, DPeshkoff approved these changes

2023-10-02 09:30 UTC, merged